version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file:
      - db.env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  resque:
    build: .
    command: bundle exec rake environment resque:work
    volumes:
      - .:/myapp
    depends_on:
      - redis
    environment:
      - QUEUE=*
  resque-scheduler:
    build: .
    command: bundle exec rake environment resque:scheduler
    volumes:
      - .:/myapp
    depends_on:
      - redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
      - redis
    env_file:
      - app.env
