 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/animal_profiles", type: :request do
  # AnimalProfile. As you add validations to AnimalProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AnimalProfile.create! valid_attributes
      get animal_profiles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      animal_profile = AnimalProfile.create! valid_attributes
      get animal_profile_url(animal_profile)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_animal_profile_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      animal_profile = AnimalProfile.create! valid_attributes
      get edit_animal_profile_url(animal_profile)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AnimalProfile" do
        expect {
          post animal_profiles_url, params: { animal_profile: valid_attributes }
        }.to change(AnimalProfile, :count).by(1)
      end

      it "redirects to the created animal_profile" do
        post animal_profiles_url, params: { animal_profile: valid_attributes }
        expect(response).to redirect_to(animal_profile_url(AnimalProfile.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AnimalProfile" do
        expect {
          post animal_profiles_url, params: { animal_profile: invalid_attributes }
        }.to change(AnimalProfile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post animal_profiles_url, params: { animal_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested animal_profile" do
        animal_profile = AnimalProfile.create! valid_attributes
        patch animal_profile_url(animal_profile), params: { animal_profile: new_attributes }
        animal_profile.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the animal_profile" do
        animal_profile = AnimalProfile.create! valid_attributes
        patch animal_profile_url(animal_profile), params: { animal_profile: new_attributes }
        animal_profile.reload
        expect(response).to redirect_to(animal_profile_url(animal_profile))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        animal_profile = AnimalProfile.create! valid_attributes
        patch animal_profile_url(animal_profile), params: { animal_profile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested animal_profile" do
      animal_profile = AnimalProfile.create! valid_attributes
      expect {
        delete animal_profile_url(animal_profile)
      }.to change(AnimalProfile, :count).by(-1)
    end

    it "redirects to the animal_profiles list" do
      animal_profile = AnimalProfile.create! valid_attributes
      delete animal_profile_url(animal_profile)
      expect(response).to redirect_to(animal_profiles_url)
    end
  end
end
