default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: myapp_development
  password: postgres

test:
  <<: *default
  database: myapp_test
